name: actions-practice
on:
  push:
    branches:
      - main
      - dev
env:
  NODE_VERSIONS: '["16", "18"]'
jobs:
  build:
    strategy:
      matrix:
        node: [16,18]
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: install deps
        run: |
          npm ci
      - name: transpile
        run: |
          npm run build
      - uses: actions/upload-artifact@v5
        with:
          name: artifacts-${{ matrix.node }}
          path: |
            dist
            node_modules
            package*.json
  test:
    needs: build
    runs-on: macos-latest
    strategy:
      matrix:
        node: [16,18]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/download-artifact@v5
        with:
          name: artifacts-${{ matrix.node }}
      - name: log ls
        run: ls node_modules/
      - name: test app
        run: |
          npm run test
  docker_build_push:
    needs: [build,test]
    runs-on: macos-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: "artifacts-18"
      - name: remove node_modules
        run: |
          rmdir node_modules
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: rameshmm/actions_practice_project:latest
