name: actions-practice
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    strategy:
      matrix:
        node: [16, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: install deps
        run: |
          npm ci
      - name: transpile
        run: |
          npm run build
      
      - name: Set artifact paths
        id: paths
        run: |
          if [ "${{ matrix.node }}" = "18" ]; then
            echo "files<<EOF
          dist
          package*.json
          Dockerfile
          EOF" >> $GITHUB_OUTPUT
          else
            echo "files<<EOF
          dist
          package*.json
          EOF" >> $GITHUB_OUTPUT
          fi
      - uses: actions/upload-artifact@v5
        with:
          name: artifacts-${{ matrix.node }}
          path: ${{ steps.paths.outputs.files }}
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: install deps
        run: |
          npm ci
      - uses: actions/download-artifact@v5
        with:
          name: artifacts-${{ matrix.node }}
      - name: test app
        run: |
          npm run test
  docker_build_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: "artifacts-18"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: rameshmm/actions_practice_project:latest
          context: .
  deploy_dev:
    needs: docker_build_push
    if: github.ref_name == 'dev'
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development Server
        run: echo "Deploying to Development Server with ${{ vars.API_URL }} and ${{ vars.DB_NAME }}..."
  deploy_prod:
    needs: docker_build_push
    if: github.ref_name == 'main'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production Server
        run: echo "Deploying to Production Server with ${{ vars.API_URL }} and ${{ vars.DB_NAME }}..."