name: actions-practice
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    strategy:
      matrix:
        node: [16, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: audit high severity vulnerabilities
        run: |
          npm audit --audit-level=high
      - name: install deps
        run: |
          npm ci
      - name: transpile
        run: |
          npm run build

      - uses: actions/upload-artifact@v5
        with:
          name: artifacts-${{ matrix.node }}
          path: |
            dist
            package*.json
            Dockerfile

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: install deps
        run: |
          npm ci
      - uses: actions/download-artifact@v5
        with:
          name: artifacts-${{ matrix.node }}
      - name: lint codebase
        run: |
          npm run lint
      - name: test app
        run: |
          npm run test

  quality-check:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: 18
          cache: 'npm'
      - name: install deps
        run: |
          npm ci
      - uses: actions/download-artifact@v5
        with:
          name: artifacts-18
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker_build_push:
    needs: quality-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download Artifacts Node 18
        uses: actions/download-artifact@v5
        with:
          name: "artifacts-18"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/arm64
          push: true
          tags: rameshmm/actions_practice_project:latest
          context: .
  deploy_dev:
    needs: docker_build_push
    if: github.ref_name == 'dev'
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development Server
        run: echo "Deploying to Development Server with ${{ vars.API_URL }} and ${{ vars.DB_NAME }}..."
  deploy_prod:
    needs: docker_build_push
    if: github.ref_name == 'main'
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production Server
        run: echo "Deploying to Production Server with ${{ vars.API_URL }} and ${{ vars.DB_NAME }}..."